spring:
  application:
    name: test_big_decimal
  datasource:
    url: jdbc:postgresql://localhost:5432/big_decimal
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
